### ISSUE TITLE
Change path_tmp so that it does not use the tmp directory

### ISSUE THREAD

**Issue by ArmandGrillet** [jrx/terraform-ansible-dcos#8]
With the current installation procedure, the files generated and then served to the masters/agents are stored by default in `/tmp/dcos-install` (this is defined [here](https://github.com/mesosphere/terraform-ansible-dcos/blob/master/roles/bootstrap/defaults/main.yml#L2). 

If the bootstrap agent restarts, these files will be wiped out which is a bad thing as the bootstrap agent should always stay up to serve new agents. The key `path_tmp` should thus be updated.

**Comment by jrx** [comment]
Thanks @ArmandGrillet good idea! I changed the default to directory on the bootstrap node to: /var/lib/dcos-bootstrap
